//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediametrie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tache
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public System.DateTime date_creation { get; set; }
        public System.DateTime date_fin { get; set; }
        public bool etat { get; set; }
        public byte priorite { get; set; }
        public int id_container { get; set; }
    
        public virtual Container Container { get; set; }
    }
}
